// Generated by https://quicktype.io

export interface AlimentosIngestaResponse {
    status:  number;
    message: string;
    data:    Alimento[];
}

export interface Alimento {
    id:                 number;
    cantidad:           number;
    carbohidratos_g:    number;
    proteina_g:         number;
    grasaTotal_g:       number;
    energia_KcaL:       number;
    estadosId:          number;
    estado:             string;
    ingestasId:         number;
    nombre:             string;
    alimentosPorcionId: number;
    alimento:           string;
    nombre_alimento:           string;
    porcion_alimento:           string;
}
