
// Generated by https://quicktype.io
export interface Data{
    codigo:number;
    pass:string;
}

export interface AuthResponse {
    status:  number;
    message: string;
    data:    Auth;
}

export interface Auth {
    id:      number;
    usuario: string;
    token:   string;
    roles:   Role[];
}

export interface Role {
    rol_Id: number;
    rol:    string;
}
