// Generated by https://quicktype.io

export interface DietasResponse {
    status:  number;
    message: string;
    data:    Dieta[];
}

export interface Dieta {
    id:         number;
    estadosId:  number;
    estado:     string;
    dietasId:   number;
    nombre:     string;
    usuariosId: number;
}
