// Generated by https://quicktype.io

export interface EjerciciosResponse {
    status:  number;
    message: string;
    data:    Ejercicio[];
}

export interface Ejercicio {
    id:                number;
    seriesId:          number;
    ejerciciosId:      number;
    nombre:            string;
    desEjercicio:      string;
    repeticiones:      number;
    peso:              string;
    estadosId:         number;
    estado:            string;
    metodoEjercicioId: number;
    metodo:            string;
    desEjercicioSerie: string;
    tiempo:            string;
}
