// Generated by https://quicktype.io

export interface GruposAlimenticiosResponse {
    status:  number;
    message: string;
    data:    GrupoAlimenticio[];
}

export interface GrupoAlimenticio {
    id:    number;
    grupo: string;
}
