// Generated by https://quicktype.io

export interface IngestasResponse {
    status:  number;
    message: string;
    data:    Ingesta[];
}

export interface Ingesta {
    id:              number;
    nombre:          string;
    descripcion:     string;
    estadosId:       number;
    estado:          string;
    dietasId:        number;
    dietas:          string;
    proteina_g:      number;
    grasaTotal_g:    number;
    carbohidratos_g: number;
    energia_KcaL:    number;
}
