// Generated by https://quicktype.io

export interface RutinaResponse {
    status:  number;
    message: string;
    data:    Rutina[];
}

export interface Rutina {
    id:         number;
    dia:        string;
    ordenDia:   number;
    estadosId:  number;
    estado:     string;
    rutinaId:   number;
    nombre:     string;
    usuariosId: number;
}
