// Generated by https://quicktype.io

export interface SeriesResponse {
    status:  number;
    message: string;
    data:    Serie[];
}

export interface Serie {
    id:              number;
    rutinaId:        number;
    nombre:          string;
    tipoEjercicioId: number;
    tipo:            string;
    estadosId:       number;
    estado:          string;
    completado:      number;
}
