// Generated by https://quicktype.io

export interface UsuarioResponse {
    status:  number;
    message: string;
    data:    Data;
}

export interface Data {
    proteinas:     number;
    grasas:        number;
    carbohidratos: number;
    kCal:          number;
    ranquin:       number;
    peso:          number;
    altura:        number;
    imc:           number;
    tipo:          string;
}
